import React, { useReducer, useEffect, useCallback, useMemo } from "react";
import useLocalStorage from "../hooks/useLocalStorage";
import {
  ACTIONS,
  PhrasesContext,
  phrasesReducer,
  type Phrase,
  type PhrasesState,
} from "./phrasesCore";

/**
 * Provider that manages the phrases state using useReducer
 * and automatically synchronizes with localStorage
 */
export const PhrasesProvider = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const [persistedPhrases, setPersistedPhrases] = useLocalStorage<Phrase[]>(
    "phrases",
    []
  );

  const initialState: PhrasesState = {
    phrases: persistedPhrases,
    filter: "",
  };

  const [state, dispatch] = useReducer(phrasesReducer, initialState);

  // Sync with localStorage
  useEffect(() => {
    setPersistedPhrases(state.phrases);
  }, [state.phrases, setPersistedPhrases]);

  const addPhrase = useCallback((text: string) => {
    const newPhrase = {
      // TODO: Migrate to UUIDs or IDs generated by the backend
      id: Date.now() + Math.random(), // Use timestamp + random to generate unique IDs temporarily
      text: text.trim(),
      createdAt: new Date().toISOString(),
    };
    dispatch({ type: ACTIONS.ADD_PHRASE, payload: newPhrase });
    // TODO: When migrating to backend requests, consider useOptimistic for instant UI feedback
  }, []);

  const deletePhrase = useCallback((id: number | string) => {
    dispatch({ type: ACTIONS.DELETE_PHRASE, payload: id });
    // TODO: When migrating to backend requests, consider useOptimistic for instant UI feedback
  }, []);

  const setFilter = useCallback((filter: string) => {
    dispatch({ type: ACTIONS.SET_FILTER, payload: filter });
  }, []);

  const value = useMemo(() => {
    return {
      phrases: state.phrases,
      filter: state.filter,
      addPhrase,
      deletePhrase,
      setFilter,
    };
  }, [state.phrases, state.filter, addPhrase, deletePhrase, setFilter]);

  return (
    <PhrasesContext.Provider value={value}>{children}</PhrasesContext.Provider>
  );
};
